name: trivy-security-scanning
on: push

permissions:
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: 'charts/milvus/full.yaml'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  images-scan:
    needs: trivy-scan
    runs-on: ubuntu-latest

    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Take list all images in side helm chart
        run: |
          cd charts/milvus
          helm template . \
              | yq '..|.image? | select(.)' \
              | sort -u > template_images.txt